excerpt_separator: <!--more-->

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

name: showzeng
title: showzeng's blog
description: Simple is beautiful
url: http://showzeng.itscoder.com/
copyright_time: 2016-2018

twitter: https://twitter.com/showzeng
weibo: https://weibo.com/showzeng
github: https://www.github.com/showzeng
email: mailto:kingstageshow@gmail.com
rss: true

show_excerpt: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
